apiVersion: v1
kind: Service
metadata:
  name: quote-cluster
  namespace: chp11-set1151
spec:
  internalTrafficPolicy: Cluster # Local, Cluster
  selector:
    app: quote
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP