apiVersion: v1
kind: Service
metadata:
  name: quote-headless
  namespace: chp11-set1143
spec:
  clusterIP: None # this creates a headless service
  selector:
    app: quote
  ports:
  - name: http
    port: 80 # port on the service's cluster IP
    targetPort: 80 # port that the pod listens to
    protocol: TCP