apiVersion: v1
kind: Pod
metadata:
  name: quiz-default
  namespace: chp08-set832
spec:
  volumes:
  - name: quiz-data
    persistentVolumeClaim:
      # Must match the metadata.name field in set832_pvc.yaml
      claimName: quiz-data-default
  containers:
  - name: quiz-api
    image: georgebaptista/quiz-api
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db