apiVersion: v1
kind: Pod
metadata:
  name: kiada-init
  namespace: chp05-set552
spec:
  initContainers:
  - name: init-demo
    image: georgebaptista/init-demo
  - name: network-check
    image: georgebaptista/network-connectivity-checker
  containers:
  - name: kiada 
    image: georgebaptista/kiada
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
