apiVersion: v1
kind: Service
metadata:
  name: quiz
  namespace: chp11-set1113
spec:
  # ClusterIP services are available only within the cluster
  type: ClusterIP
  # Specify which pods are part of this service
  selector:
    app: quiz
  ports:
  - name: http
    # Port 80 of this service is mapped to port 80 in the pods backing this service
    port: 80
    # This must be 8080, since the pod manifest specifies it as so
    targetPort: 8080
    protocol: TCP