apiVersion: v1
kind: Pod
metadata:
  name: kiada
  namespace: chp09-set912
spec:
  containers:
  - name: kiada
    image: georgebaptista/kiada:0.4
    imagePullPolicy: IfNotPresent
    args:
    - --listen_port
    - $(LISTEN_PORT)
    # Set environment variables
    env:
    - name: LISTEN_PORT
      value: "8080"
    - name: POD_NAME
      value: kiada
    - name: INITIAL_STATUS_MESSAGE
      value: This status message is set in the pod spec.
    - name: INITIAL_STATUS_MESSAGE_DYNAMIC
      value: My name is $(POD_NAME). I run NodeJS version $(NODE_VERSION).
    ports:
    - name: http
      containerPort: 8080