apiVersion: v1
kind: Pod
metadata:
  name: env-var-references-in-shell
  namespace: chp09-set912
spec:
  containers:
  - name: main
    image: alpine
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - 'echo "Hostname is $HOSTNAME."; sleep infinity'
