apiVersion: v1
kind: Pod
metadata:
  name: quiz
  namespace: chp08-set822
spec:
  containers:
  - name: quiz-api
    image: luksa/quiz-api:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5