apiVersion: v1
kind: Service
metadata:
  name: quiz
  namespace: chp11-set1112
  labels:
    app: quiz
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: quiz
    rel: stable