apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: chp06-set661
  labels:
    app: mongodb-pvc
spec:
  # For dynamic provisioning, specify name of storage class resource
  # After creating claim, PV is created by the Storage Class provisioner
  # This DOES NOT use the default standard storage class, since we specify
  # storageClassName property here
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce # single client, RW

