apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    app: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce # single client, R+W
  - ReadOnlyMany # multiple clients, R
  persistentVolumeReclaimPolicy: Retain # after claim release
  hostPath: # persistent volume backing object
    path: /tmp/mongodb
