apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: chp06-set654
  labels:
    app: mongodb
    env: dev
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      # reference to PVC name
      claimName: mongodb-pvc

