apiVersion: v1
kind: Pod
metadata:
  name: kiada
  namespace: chp09-set923b
spec:
  containers:
  - name: kiada
    image: georgebaptista/kiada:0.4
    imagePullPolicy: Always
    env:
    - name: POD_NAME
      value: kiada
    envFrom:
    - prefix: CONFIG_
      configMapRef:
        name: kiada-config
        optional: true
    ports:
    - name: http
      containerPort: 8080


