apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-default
  namespace: chp06-set663
  labels:
    app: mongodb-pvc-default
spec:
  # To enable dynamic provisioning, omit storageClassName field
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce # single client, RW

