kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-ssd-on-kind-worker
spec:
  accessModes:
  - ReadWriteOnce
  # Refers to storageClass object defined in set841_sc_no_provisioner.yaml
  storageClassName: local 
  capacity:
    storage: 100Mi
  local:
    path: /mnt/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
        #- key: nodeName 
          operator: In
          values:
          #- worker1
          - main