apiVersion: v1
kind: PersistentVolume
metadata:
  name: quiz-data
  # No namespace for PVs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # single client, R+W
    - ReadOnlyMany # multiple clients, R
  persistentVolumeReclaimPolicy: Retain # after claim release
  hostPath: # persistent volume backing on microk8s
    path: /var/quiz-data