apiVersion: v1
kind: Pod
metadata:
  name: quiz
  namespace: chp08-set823
spec: 
  # Make this pod use the quiz-data PVC
  volumes:
  - name: quiz-data
    persistentVolumeClaim:
      claimName: quiz-data
  containers:
  - name: quiz-api
    image: georgebaptista/quiz-api:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5
    imagePullPolicy: IfNotPresent
    # Mount the volume the same way other volume types are mounted
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db