# https://keathmilligan.net/kubernetes-for-internal-infrastructure

apiVersion: v1
kind: Namespace
metadata:
  name: chp08-set832
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: chp08-set832
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.26
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: "100M"
            cpu: "0.1"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  namespace: chp08-set832
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: chp08-set832
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None