apiVersion: v1
kind: Pod
metadata:
  name: poststart-httpget
  namespace: chp06-set631b
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
    lifecycle:
      postStart:
        httpGet:
          host: jsonplaceholder.typicode.com
          port: 80
          path: /posts
