apiVersion: v1
kind: Service
metadata:
  name: fortune
  namespace: chp06-set621
spec:
  ports:
  - port: 80 # incoming 
    # the pod containerPort is 80, so our targetPort is 80
    targetPort: 80 # outgoing target 
    protocol: TCP
  selector:
    app: fortune

