apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data-fast
  namespace: chp08-set833
spec:
  # We don't do dynamic provisioning here
  # This claim requests this storage class be used to provision the volume
  storageClassName: fast
  resources:
    requests: # Volume must provide at least same space as specified PV
      storage: 100Mi
  accessModes:
  - ReadWriteOnce # same as PV