apiVersion: v1
kind: Pod
metadata:
  name: kiada-liveness
  namespace: chp06-set625
spec:
  containers:
  - name: kiada 
    image: georgebaptista/kiada:0.1
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    livenessProbe:
      exec:
        command:
        - /usr/bin/healthcheck
      periodSeconds: 2
      timeoutSeconds: 1
      failureThreshold: 1