apiVersion: v1
kind: Pod
metadata:
  name: kiada-ssl-shortgraceperiod
  namespace: chp06-set643
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: kiada
    image: luksa/kiada:0.3
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901