apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data
  # We can have namespaces for PVCs
  namespace: chp08-set822
spec:
  resources:
    requests: # Volume must provide at least same space as specified PV
      storage: 1Gi
  accessModes:
  - ReadWriteOnce # same as PV
  storageClassName: "" # must be empty string to disable dynamic provisioning
  volumeName: quiz-data # Claim the quiz-data PV, which has this name