apiVersion: v1
kind: Service
metadata:
  name: quiz
  namespace: chp13-set1331
  labels:
    app: quiz
spec:
  type: ClusterIP
  selector:
    app: quiz
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP