apiVersion: v1
kind: Service
metadata:
  name: quiz-pods
  namespace: chp15-set1525
spec:
  clusterIP: None # Create a headless service
  publishNotReadyAddresses: true
  selector:
    app: quiz
  ports:
  - name: mongodb 
    port: 27017