apiVersion: v1
kind: Pod
metadata:
  name: kiada
  namespace: chp09-set923
spec:
  containers:
  - name: kiada
    image: georgebaptista/kiada:0.4
    imagePullPolicy: Always
    env:
    - name: POD_NAME
      value: kiada
    - name: INITIAL_STATUS_MESSAGE
      valueFrom:
        configMapKeyRef:
          name: kiada-config
          key: status-message
          optional: true
    ports:
    - name: http
      containerPort: 8080