apiVersion: v1
kind: ConfigMap
metadata:
  name: kiada-config
  namespace: chp09-set923
data:
  status-message: This status message is set in the kiada-config config map.
  test1: This is test1
  test2: This is test2
  