apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-claim
  namespace: chp10-set1032b
spec:
  selector:
    matchLabels:
      type: ssd
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: ""
