apiVersion: v1
kind: Pod
metadata:
  name: quiz-default
  namespace: chp08-set833
spec:
  volumes:
  - name: quiz-data
    persistentVolumeClaim:
      # Must match the metadata.name field in set833_pvc.yaml
      claimName: quiz-data-fast
  containers:
  - name: quiz-api
    image: luksa/quiz-api:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db