apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data
  namespace: chp11-set1112
  labels:
    app: quiz
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce

