apiVersion: v1
kind: Pod
metadata:
  name: quiz
  namespace: chp08-set821
spec:
  containers:
  - name: quiz-api
    image: georgebaptista/quiz-api
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5