apiVersion: v1
kind: Pod
metadata:
  name: kiada
  namespace: chp09-set911
spec:
  containers:
  - name: kiada
    image: georgebaptista/kiada:0.4
    command: 
    - node
    - --cpu-prof
    - --heap-prof
    - app.js
    ports:
    - name: http
      containerPort: 8080