apiVersion: v1
kind: Service
metadata:
  name: kiada
  namespace: chp11-set1121
spec:
  type: NodePort
  selector:
    app: kiada
  ports:
  - name: http
    port: 80 # port on the service's cluster IP
    nodePort: 30080 # accessible port on each cluster nodes
    targetPort: 8080 # port that the pod listens to
  - name: https
    port: 443
    nodePort: 30443
    targetPort: 8443