apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data
  namespace: chp12-set1231
  labels:
    app: quiz
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce