apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiada
  namespace: chp14-set1425
  labels:
    app: kiada
    rel: stable
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  # Each pod must be ready for 60 seconds before it is considered available
  minReadySeconds: 60
  progressDeadlineSeconds: 120
  replicas: 3
  selector:
    matchLabels:
      app: kiada
      rel: stable
  template:
    metadata:
      labels:
        app: kiada
        rel: stable
        ver: '0.8'
    spec:
      containers:
      - name: kiada
        # This version fails after a given amount of time
        image: luksa/kiada:0.8
        imagePullPolicy: Always
        env:
          # Set amount of seconds before the service fails
        - name: FAIL_AFTER_SECONDS
          value: "30"
        - name: QUOTE_URL
          value: http://quote/quote
        - name: QUIZ_URL
          value: http://quiz
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: http
          containerPort: 8080
        # Run on startup, and then every 10 seconds
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 1
          httpGet:
            port: 8080
            path: /healthz/ready
            scheme: HTTP
      - name: envoy
        image: envoyproxy/envoy:v1.14.1
        volumeMounts:
        - name: etc-envoy
          mountPath: /etc/envoy
          readOnly: true
        ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 1
          httpGet:
            port: admin
            path: /ready
      volumes:
      - name: etc-envoy
        projected:
          sources:
          - configMap:
              name: kiada-envoy-config
          - secret:
              name: kiada-tls
              items:
              - key: tls.crt
                path: example-com.crt
              - key: tls.key
                path: example-com.key
                mode: 0600