apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      hostPathProvisionerIdentity: actionbook-v1
      pv.kubernetes.io/provisioned-by: microk8s.io/hostpath
    creationTimestamp: "2022-09-03T11:57:54Z"
    finalizers:
    - kubernetes.io/pv-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:hostPathProvisionerIdentity: {}
            f:pv.kubernetes.io/provisioned-by: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:hostPath:
            .: {}
            f:path: {}
            f:type: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: hostpath-provisioner
      operation: Update
      time: "2022-09-03T11:57:54Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-09-03T11:57:54Z"
    name: pvc-839738ef-e37f-4e04-b7f4-a0992fdf84c4
    resourceVersion: "13995"
    selfLink: /api/v1/persistentvolumes/pvc-839738ef-e37f-4e04-b7f4-a0992fdf84c4
    uid: 277cca42-b944-4dfd-b74c-f210696762be
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: test-pvc
      namespace: test
      resourceVersion: "13986"
      uid: 839738ef-e37f-4e04-b7f4-a0992fdf84c4
    hostPath:
      path: /var/snap/microk8s/common/default-storage/test-test-pvc-pvc-839738ef-e37f-4e04-b7f4-a0992fdf84c4
      type: ""
    persistentVolumeReclaimPolicy: Delete
    storageClassName: microk8s-hostpath
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
