apiVersion: v1
kind: Pod
metadata:
  name: kiada
  namespace: chp10-set1011
spec:
  containers:
  - name: kiada
    image: georgebaptista/kiada:0.4
    imagePullPolicy: Always
    command: 
    - node
    - --cpu-prof
    - --heap-prof
    - app.js
    ports:
    - name: http
      containerPort: 8080